// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tmmkazidubfjbfrumayn.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbWthemlkdWJmamJmcnVtYXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1MjAzNzksImV4cCI6MjA0NzA5NjM3OX0.jvK7c2bdqWTLLmsffkAxiZCNrYOAboDyN7Lw7QAHlos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);